crm-dotnet/Controllers/TauxAlerteController.cs
using crm_dotnet.Models.entity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace crm_dotnet.Controllers
{
    public class TauxAlerteController : Controller
    {
        private static readonly HttpClient client = new HttpClient();
        string project_url = "http://localhost:8084/";
        public async Task<IActionResult> Index()
        {
            HttpResponseMessage response = await client.GetAsync(project_url + "api/get-allTaux");
            response.EnsureSuccessStatusCode();
            string json = await response.Content.ReadAsStringAsync();


            TauxAlerteBudget[] listTaux = (TauxAlerteBudget[])JsonConvert.DeserializeObject<TauxAlerteBudget[]>(json);
            ViewData["listTaux"] = listTaux;
            return View("Insert");
        }

        [HttpPost]
        public async Task<IActionResult> Insert(string taux)
        {
            string url = project_url + "api/taux-alerte/insert";

            var values = new Dictionary<string, string>
            {
                {"taux", taux }
            };

            var content = new FormUrlEncodedContent(values);
            var response = await client.PostAsync(url, content);

            return RedirectToAction("Index");
        }
    }
}

crm-dotnet/Views/TauxAlerte/Insert.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using crm_dotnet.Models.entity
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    TauxAlerteBudget [] listTaux = (TauxAlerteBudget[])ViewData["listTaux"];
}

<div class="loader"></div>
    <div id="app">
        <div class="main-wrapper main-wrapper-1">
            @Html.Partial("_leftSideBar")
            <!-- Main Content -->
            <div class="main-content">
                <section class="section">
                    <div class="section-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h4>Modification de taux d'alerte de budget</h4>
                                    </div>
                                    <div class="card-body">
                                        <form asp-controller="TauxAlerte" asp-action="Insert" method="post">
                                           
                                            <div class="form-group">
                                                <label>Taux %</label>
                                                <input class="form-control" type="number" name="taux" step="0.01" min="0" required/>
                                            </div>
                                           
                                            <button type="submit" class="btn btn-primary">Modifier</button>
                                           
                                        </form>

                                    </div>
                                </div>
                                <div class="card">
                                    <div class="card-header">
                                        <h4>Historique des taux</h4>
                                    </div>
                                    <div class="card-body">
                                        <div class="table-responsive">
                                            <table class="table table-striped" id="table-1">
                                                <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>taux %</th>
                                                    <th>Date d'ajout</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach (var t in listTaux)
                                                    {
                                                        <tr>
                                                            <td>@t.Id</td>
                                                            <td>@t.Taux</td>
                                                            <td>@t.Date_ajout</td>
                                                        </tr>
                                                    }
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>